<?php

namespace II\Bundle\CongeBundle\Entity;

/**
 * CongeConventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CongeConventionRepository extends \Doctrine\ORM\EntityRepository
{
}
