<?php

namespace II\Bundle\CongeBundle\Entity;

/**
 * CongeUtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CongeUtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
